put:
    path: /values/{key}
    controller: App\Controller\PutValueController
    methods: ["PUT"]

delete:
    path: /values/{key}
    controller: App\Controller\DeleteValueController
    methods: ["DELETE"]

get:
    path: /values/{key}
    controller: App\Controller\GetValueController
    methods: ["GET"]
